global:
  scrape_interval: 3s

scrape_configs:
- job_name: 'nginx'
  static_configs:
    - targets: ['nginx-exporter:9113']

- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'api1'
  metrics_path: /api/metrics
  static_configs:
  - targets: ['api1:3000']

- job_name: 'api2'
  metrics_path: /api/metrics
  static_configs:
    - targets: ['api2:3000']

- job_name: 'email-service'
  static_configs:
    - targets: ['email-service:3000']

- job_name: 'mongo'
  static_configs:
    - targets: ['mongo-exporter:9216']

- job_name: 'kafka'
  static_configs:
    - targets: ['kafka-exporter:9308']